[package]
name = "buckets"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = {version = "0.28.1", features = ["event-stream"]}
futures = "0.3.31"
itertools = "0.14.0"
rand = "0.9.0"
ratatui = "0.29.0"
tokio = {version = "1.44.1", features = ["full"]}
tokio-util = "0.7.14"
